package_assets: on
embed_assets: datauri

javascripts:
  all:
    - public/javascripts/typekit.js
    - public/javascripts/spring.js
    - public/javascripts/jquery/jquery-1.4.4.js
    - public/javascripts/jquery/jquery.templates/beta1/jquery.tmpl.js
    - public/javascripts/jquery/jquery.timeago/0.9.2/jquery.timeago.js
    - public/javascripts/jquery/jquery.timeago/common/jquery.timeago.no.js
    - public/javascripts/jquery/jquery.tools/1.2.5/tooltip.js
    - public/javascripts/jquery/jquery.cookie/2010-01-08/jquery.cookie.js
    - public/javascripts/jquery/jquery.imgloaded/2010-08-23/ahpi.imgload.js
    - public/lib/plupload/js/plupload.full.min.js
    - public/javascripts/plupload-config.js
    - public/javascripts/maptastic.js
    - public/javascripts/rails.js
    - public/javascripts/mime-tools.js
    - public/javascripts/application.js
    - public/javascripts/document-ready.js
    - public/javascripts/article-map.js

stylesheets:
  all:
    - public/stylesheets/reset.css
    - public/stylesheets/application.css
    - public/stylesheets/jquery-ui.css
